---
- name: Data Upload Check
  hosts: all
  become: true
  gather_facts: no
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  tasks:

    - name: Copy script from local machine to remote hosts
      copy:
        src: /etc/ansible/playbooks/shipmate/script/data_check.sh
        dest: /tmp/data_check.sh
      ignore_errors: true

    - name: Set execute permission on the script
      file:
        path: /tmp/data_check.sh
        mode: '0755'
      ignore_errors: true

    - name: Run Data Check script
      shell: bash /tmp/data_check.sh
      ignore_errors: true

    - name: Fetch the log file to the local machine
      fetch:
        src: /tmp/logs.txt
        dest: ~/Documents/Data Upload Check/data_upload_logs_{{ inventory_hostname }}.txt
        flat: yes
      ignore_errors: true

    - name: Delete the log file and the script file from the remote machine
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/data_logs.txt
        - /tmp/logs.txt
        - /tmp/data_check.sh
      ignore_errors: true