---
- name: Start ship version
  hosts: ships
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no
  ignore_unreachable: yes
  ignore_errors: yes

  vars:
    ansible_become_password: "Orca123"

  tasks:
    - name: Get the version from running container
      shell: >
        sudo docker ps | awk '$NF == "system-manager" {split($2, a, ":"); print a[2]}'
      register: current_version
      changed_when: false

    - name: Run ship-cli with the current version
      shell: >
        sudo docker run --rm -it 
        -e CUDA_VERSION=$(nvidia-smi | grep 'CUDA Version:' | cut -d ':' -f3 | sed -r 's/[|]+/ /g' | xargs) 
        -e DISPLAY=$(w -hs | grep -Po "[ \t]:[\.0-9A-Za-z:]+[ \t]" | sort -u | xargs) 
        -e AUDIO_GROUP=$(getent group audio | cut -d: -f3) 
        -e XDG_RUNTIME_DIR_VALUE=${XDG_RUNTIME_DIR} 
        -v ~/.docker/config.json:/root/.docker/config.json 
        -v /var/run/docker.sock:/var/run/docker.sock 
        -v /orcaai/orcaai-storage:/orcaai/orcaai-storage 
        -v /dev:/dev 
        -v /lib/modules:/lib/modules 
        -v /etc/rc.local:/host/rc.local 
        -v /run/systemd/system:/run/systemd/system 
        -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket 
        -v $XAUTH:/root/.Xauthority 
        -v /tmp/.X11-unix:/tmp/.X11-unix 
        -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR_VALUE}/pulse/native 
        --network host --privileged --cap-add=ALL 
        registry.gitlab.com/orca_ai/orcaai-ship/ship-cli:{{ current_version.stdout }} 
        make start-version VERSION={{ current_version.stdout }}
      when: current_version.stdout is defined and current_version.stdout != ""
      register: docker_run_result
      changed_when: "'error' not in docker_run_result.stderr"

    - name: Debug output (optional)
      debug:
        msg: "Successfully started the {{ current_version.stdout }} version"
      when: docker_run_result.rc == 0
